#!/bin/bash
usage () {
  echo "usage: $(basename "$0") xyz_lexicon.txt"
  echo "writes xyz_lexicon.tab and xyz_lexicon.log"
  exit
}

[[ $1 = *.txt && -e $1 ]] || usage
txt=$1
pfx=${txt%.txt}

time ./lex2tab.py "$txt" > "$pfx.tab" 2> "$pfx.log"
